### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by afercher** [storevision/webstore-frontend#6]
- It must be possible to register a new user.
Please note the following registration criteria.
  - [ ] Email
  - [ ] First Name
  - [ ] Last Name
  - [ ] Password
  - [ ] Password to check the input

To complete the registration there must be a button with the label...
- [x] "Register"
- [ ] ~"Cancel"~ (https://github.com/storevision/webstore-frontend/issues/6#issuecomment-2516672585)

**Comment by CommanderRedYT** [comment]
I propose to remove the button "Cancel" as the user can go back via browser history.

**Comment by afercher** [comment]
No objection, leave it out.

**Comment by CommanderRedYT** [comment]
I also propose to combine first name and last name
